name: ncbi-demo
channels:
  - conda-forge
  - bioconda
dependencies:
  - ncbi-datasets-cli
  - sra-tools
  - magicblast
  - blast
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
